server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.home.cn:3306/mine_shop?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
dubbo:
  registry:
    address: zookeeper://192.168.30.128:2181,192.168.30.129:2181,192.168.30.130:2181
  application:
    name: manage-service
  protocol:
    name: dubbo
    port: 20885
  scan:
    base-packages: com.mine.manageservice