server:
  port: 8083
dubbo:
  scan:
    base-packages: com.mine.manageweb
  application:
    name: manage-web
  protocol:
    name: dubbo
    port: 20884
  registry:
    protocol: zookeeper
    address: 192.168.30.128:2181,192.168.30.129:2181,192.168.30.130:2181