spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.home.cn:3306/mine_shop?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

server:
  port: 8082
dubbo:
  registry:
    simplified: true
    address: zookeeper://192.168.30.128:2181,192.168.30.129:2181,192.168.30.129:2181
  scan:
    base-packages: com.mine.user
  protocol:
    name: dubbo
    port: 20881
  application:
    name: user-service