server:
  port: 8081
dubbo:
  application:
    name: order-web
  protocol:
    name: dubbo
    port: 20882
  registry:
    simplified: true
    address: zookeeper://192.168.30.128:2181,192.168.30.129:2181,192.168.30.129:2181
  scan:
    base-packages: com.mine.orderweb
